package hgc.flowsyncapi.service;
import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.*;import hgc.flowsyncapi.dto.*;import hgc.flowsyncapi.entity.User;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;
import java.net.URI;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.time.Duration;import java.util.*;import java.util.stream.Collectors;
@Service public class QwenService{
 private final ObjectMapper json;@Value("${dashscope.api-key:}")private String key;@Value("${dashscope.model:qwen-plus}")private String model;
 public QwenService(ObjectMapper j){json=j;}
 public String suggestion(AiTaskSuggestionRequest r){String fallback="1. 子任务：明确目标、准备资料、执行主体、检查提交。\n2. 执行顺序：确认需求后分工实施，最后统一验收。\n3. 风险提醒：注意截止时间、责任人和成果标准。";if(key==null||key.isBlank())return fallback;try{return call("你是一个简单直接的项目任务助手。请用最容易理解的中文输出，给出：1. 建议拆分的子任务；2. 执行顺序；3. 风险提醒。控制在300字以内。","项目名称："+safe(r.getProjectName())+"\n任务标题："+safe(r.getTaskTitle())+"\n任务说明："+safe(r.getTaskDescription()));}catch(Exception e){return fallback;}}
 public AiTaskPlanResponse plan(AiTaskPlanRequest r,List<User> users){if(key==null||key.isBlank())return fallback();String members=users.stream().map(u->u.getId()+" - "+u.getRealName()).collect(Collectors.joining("\n"));String system="你是一个项目任务拆解助手。请把大任务拆成可以直接执行的小任务。每个任务必须使用成员名单中已有的 assigneeId。只返回严格 JSON，不要解释，不要 markdown。";String prompt="项目名称："+safe(r.getProjectName())+"\n任务目标："+safe(r.getGoal())+"\n补充说明："+safe(r.getDescription())+"\n成员名单：\n"+members+"\n格式：{\"summary\":\"...\",\"items\":[{\"title\":\"...\",\"description\":\"...\",\"priority\":\"高\",\"suggestedDays\":3,\"assigneeId\":1}]}";try{AiTaskPlanResponse x=json.readValue(strip(call(system,prompt)),AiTaskPlanResponse.class);Set<Long>valid=users.stream().map(User::getId).collect(Collectors.toSet());Long first=users.isEmpty()?null:users.get(0).getId();for(AiTaskPlanItem i:x.getItems()){if(i.getAssigneeId()==null||!valid.contains(i.getAssigneeId()))i.setAssigneeId(first);}return x;}catch(Exception e){return fallback();}}
 private String call(String system,String user)throws Exception{ObjectNode root=json.createObjectNode();root.put("model",model);ArrayNode messages=json.createArrayNode();messages.addObject().put("role","system").put("content",system);messages.addObject().put("role","user").put("content",user);root.putObject("input").set("messages",messages);root.putObject("parameters").put("result_format","message");HttpRequest req=HttpRequest.newBuilder(URI.create("https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation")).timeout(Duration.ofSeconds(60)).header("Authorization","Bearer "+key).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(json.writeValueAsString(root),StandardCharsets.UTF_8)).build();HttpResponse<String>res=HttpClient.newHttpClient().send(req,HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));if(res.statusCode()/100!=2)throw new IllegalStateException("千问调用失败");return json.readTree(res.body()).path("output").path("choices").get(0).path("message").path("content").asText();}
 private AiTaskPlanResponse fallback(){AiTaskPlanResponse r=new AiTaskPlanResponse();r.setSummary("AI 服务暂不可用，已生成标准兜底方案，请选择负责人后导入。");r.setItems(Arrays.asList(item("准备资料","收集需求、材料和约束条件。","中",2),item("执行主体","按目标完成主要实施工作。","高",5),item("检查总结","检查质量、修正问题并形成总结。","中",2)));return r;}
 private AiTaskPlanItem item(String a,String b,String c,int d){AiTaskPlanItem i=new AiTaskPlanItem();i.setTitle(a);i.setDescription(b);i.setPriority(c);i.setSuggestedDays(d);return i;}private String safe(String x){return x==null?"":x;}private String strip(String x){return x.replace("```json","").replace("```","").trim();}
}
